### ISSUE TITLE
Incorrect configuration when use `arm64` or `x86_64`

### ISSUE THREAD

**Issue by kiyochinh** [vikage/DemoBazelTulsi#1]
## Issue

I use Apple M1 silicon (arm64), but always show error when build and run app to simulator, or you can try change target build to `Any iOS Device (arm64)` and observe results.

![Screen Shot 2022-04-21 at 20 23 06](https://user-images.githubusercontent.com/81249662/164467286-6804893a-faeb-4d1b-8289-9fca0ba08e5d.png)

I also tried building on my real device but still not working and got the same error.

🤔 I think this issue is caused by some configuration of `tulsi` incorrect.
 
## Expected

Can work hybrid between **x86_64** and **arm64** 
 
## Steps to reproduce

1. Checkout code from: https://github.com/vikage/DemoBazel
2. Run command: `bazel build @Firebase//: Firebase ` → Build third-party
3. Run command: `bazel build //App:ios_app`
4. Open `tulsi` project and generate a xcode project
5. Observe result

**Comment by vikage** [comment]
@kiyochinh Your issue is missing the provisioning profile configuration of ios_application target when building app for the device. More detail: https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application

**Comment by kiyochinh** [comment]
@vikage thank you 😄
